If:
  PathMatch: .*\.h
  CompileFlags:
    Add: [-xc, -xc-header, ]
  
---

CompileFlags:
  Add:
    - -I/usr/local/include/**
    - -I/usr/include/**
    - -Wall
    - -Wextra
    - -Wconversion
    - -Wfloat-equal

Index:
  Background: Skip

Diagnostics:
  Suppress: ["pp_including_mainfile_in_preamble", 
"misc-definitions-in-headers"]
